# Generated by Django 6.0.1 on 2026-01-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_ground', models.CharField(blank=True, max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oppositions', to='clubs.club')),
            ],
        ),
    ]
