# Generated by Django 6.0.1 on 2026-01-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('yes', 'Available'), ('no', 'Not Available'), ('maybe', 'Maybe')], default='maybe', max_length=5)),
                ('selected', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='clubs.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_appearances', to='clubs.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
