# Generated by Django 6.0.1 on 2026-01-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_matchplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opposition',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
